### ISSUE TITLE
upload-readme-assets

### ISSUE THREAD

**Issue by seventanyb** [os2edu/classroom-grading-template#1]
<img width="1717" alt="action" src="https://user-images.githubusercontent.com/108247373/179374179-56459b7e-c653-4ea2-8d64-a66a8288ae0c.png">

<img width="917" alt="fork" src="https://user-images.githubusercontent.com/108247373/179374180-2c4ae639-3295-409d-8fcc-610bd018bacb.png">

<img width="380" alt="shortcut" src="https://user-images.githubusercontent.com/108247373/179374302-0c54ef62-9338-4122-89f9-47d7f8dc2fab.png">

**Comment by seventanyb** [comment]
<img width="973" alt="config2" src="https://user-images.githubusercontent.com/108247373/179375014-8f81bc75-d49e-41fe-ae53-be5c8e483e84.png">

**Comment by july-12** [comment]
<img width="1154" alt="workflow" src="https://user-images.githubusercontent.com/920487/179375397-3e26959c-675b-48ad-b229-09726f697646.png">

<img width="1159" alt="gh-pages" src="https://user-images.githubusercontent.com/920487/179375401-0d57b303-36c9-4599-88fd-0f4d93a095cd.png">

**Comment by july-12** [comment]
<img width="1146" alt="pat" src="https://user-images.githubusercontent.com/920487/179375564-83b9360d-14be-470f-bae6-118098139fd6.png">

<img width="1143" alt="auth-token" src="https://user-images.githubusercontent.com/920487/179375600-8fc6102f-b7d0-40a2-a7d1-df026bbc290c.png">

**Comment by july-12** [comment]
<img width="1733" alt="workflow-enable" src="https://user-images.githubusercontent.com/920487/179376541-0a906707-1a43-4d37-ab50-d19c8812f87b.png">

**Comment by seventanyb** [comment]
<img width="664" alt="classroomName" src="https://user-images.githubusercontent.com/108247373/179397657-f8bbc0cf-958a-4edb-bf98-477591de013f.png">

**Comment by july-12** [comment]
<img width="1084" alt="session" src="https://user-images.githubusercontent.com/920487/179450068-c620e185-583f-4f83-a372-ee2c2825b805.png">

**Comment by july-12** [comment]
<img width="954" alt="config3" src="https://user-images.githubusercontent.com/920487/179450921-b7a53c40-cccb-4648-8ea8-8000f8f02432.png">

**Comment by july-12** [comment]
<img width="974" alt="fork" src="https://user-images.githubusercontent.com/920487/179538395-b8df34ad-5bb5-4ffb-88e5-394f39121068.png">

**Comment by seventanyb** [comment]
<img width="843" alt="config" src="https://user-images.githubusercontent.com/108247373/179552983-c3807fbf-bcbf-4a24-9bf6-9116d6ca8137.png">
