### ISSUE TITLE
Issue of Missing Initial Configuration in README

### ISSUE THREAD

**Issue by yzouchen** [os2edu/classroom-grading-template#2]
After a fork, It seems that we need to initialize the `src/data.json` file to run the autograding.
Of course, after the initialization first time, `'updata' commit` will auto-update that file.

This configuration haven't been mentioned in the README file currently.

Our solution of the `src/data.json` file as follow:
```
{
    "classrooms": [
        {
            "title": "Your classroom title",
            "id": "Your classroom id",
            "desc": "",
            "assignments": [
                {
                    "id": "your assignment id",
                    "title": "your assignment title",
                    "branches": [
                        "selected branch"
                    ],
                    "student_repositories": [

                    ]
                }
            ]
        }
    ],
    "latest_updated_at": " ",
    "apiUseCount":  0
} 
```

**Comment by july-12** [comment]
@yzouchen thank for your feedback.

yeah  it really is issue in __parsing classroom data method__ at first time to execute autograding action.  you are excellent as finding the way out to pass throngh that problem.  Did you finally  get your github pages deploy successfully?

I have resolved the issue  at this commit https://github.com/os2edu/classroom-grading-template/commit/9771501bd2c4f62f88ea7145a11449665ca1c6b6

calling me anytime when you get problem.
